GET {{host}}/clientes/99/extrato

> {%
    client.test("Status code is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.length !== 0, "Response body is empty");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
    "valor": 1,
    "tipo" : "c",
    "descricao" : "descricao"
}

> {%
    client.test("Status code is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.length > 0, "Response body is empty");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo" : "d",
  "descricao" : "descricao"
}

> {%
    client.test("Status code is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.length > 0, "Response body is empty");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": 1000000,
  "tipo" : "d",
  "descricao" : "descricao"
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
        client.assert(response.body.length == 0, "Response body is not empty");
    });
%}


###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo" : "",
  "descricao" : "descricao"
}

> {% 
 client.test("Status code is 422", function() {
   client.assert(response.status === 422, "Response status is not 422");
 });
 %}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo" : "x",
  "descricao" : "descricao"
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": null,
  "tipo" : "x",
  "descricao" : "descricao"
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo" : null,
  "descricao" : "descricao"
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": 1.2,
  "tipo" : "d",
  "descricao" : "descricao"
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": -1,
  "tipo" : "d",
  "descricao" : "descricao"
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": -1,
  "tipo" : "d",
  "descricao" : "123456789 descricao"
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": -1,
  "tipo" : "d",
  "descricao" : ""
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
    });
%}

###
POST {{host}}/clientes/99/transacoes
Content-Type: application/json

{
  "valor": -1,
  "tipo" : "d",
  "descricao" : null
}

> {%
    client.test("Status code is 422", function() {
        client.assert(response.status === 422, "Response status is not 422");
    });
%}